### PR TITLE
Adding avax fuji testnet to truffle config

### PR DESCRIPTION
**Pull request by fqlx**
Adding Avax mainnet and fuji testnet to Opyn truffle config

### CODE REVIEW

**Review by haythem96 — APPROVED** [review]
LGTM.

**Review by aparnakr — APPROVED** [review]

**Review by antoncoding — APPROVED** [review]

**Comment by antoncoding** [comment]
@fqlx I think our old circle ci setting was blocking builds from forked repos, can you try pushing a tag or force a re-push to see if the check works now? thanks

**Comment by fqlx** [comment]
I will switch the Owner to Opyn's multisig, when we launch, likely before end of the year. 

**Avalanche Mainnet Address**

AddressBook: [0xBCa124824326CF8aBc5E2E569FFf3A6f17110510](https://snowtrace.io/address/0xBCa124824326CF8aBc5E2E569FFf3A6f17110510)
OtokenFactory: [0x25bC1cD298512885F0e452833198BCBb149f66a5](https://snowtrace.io/address/0x25bc1cd298512885f0e452833198bcbb149f66a5)
Otoken: [0x459a8Ba81a0f0eA672856d2415e25E50D4224677](https://snowtrace.io/address/0x459a8Ba81a0f0eA672856d2415e25E50D4224677)
Whitelist: [0xe9963AFfc9a53e293c9bB547c52902071e6087c9](https://snowtrace.io/address/0xe9963AFfc9a53e293c9bB547c52902071e6087c9)
Oracle: [0x5c76E757138379E376D1Cb9C18723f884df5e8Eb](https://snowtrace.io/address/0x5c76E757138379E376D1Cb9C18723f884df5e8Eb)
MarginPool: [0xCCF6629aEaB734E621Cc59EBb0297196774fDb9D](https://snowtrace.io/address/0xCCF6629aEaB734E621Cc59EBb0297196774fDb9D)
MarginCalculator: [0xBD5A1Dc654B5476B94F81755E68d1C8f0AAc2AFd](https://snowtrace.io/address/0xBD5A1Dc654B5476B94F81755E68d1C8f0AAc2AFd)
MarginVault: [0x8b5685586f43c07aa0F911Bb5d5DB8B56252858a](https://snowtrace.io/address/0x8b5685586f43c07aa0F911Bb5d5DB8B56252858a)
Controller: [0xEadF3d94b902c06c13A2e64b223B1DF5057Aa23d](https://snowtrace.io/address/0xEadF3d94b902c06c13A2e64b223B1DF5057Aa23d)
OwnedUpgradeabilityProxy: [0x9e3b94819aaF6de606C4Aa844E3215725b997064](https://snowtrace.io/address/0x9e3b94819aaF6de606C4Aa844E3215725b997064)

WAVAX ChainLinkerPricer: [0x35483d546c8C2D474e5E135DBFc55D4dFF8ba7B4](https://snowtrace.io/address/0x35483d546c8C2D474e5E135DBFc55D4dFF8ba7B4)
WBTC ChainLinkerPricer: [0xA3F6D62d480BBbB97ec7e8834D562AB6598397Cb](https://snowtrace.io/address/0xA3F6D62d480BBbB97ec7e8834D562AB6598397Cb)

Owner: 0xd4816D144C005B29dF24C8eb1865fB8A1e79FdDE (ben@ribbon.finance)

**Avalanche Fuji Address**

AddressBook: [0xa25D74a18a22d0426431B0E580432F294b502347](https://testnet.snowtrace.io/address/0xa25D74a18a22d0426431B0E580432F294b502347)|
OtokenFactory: [0x3aB375D57EbB733E735a17eDFd3F973f6BC5de21](https://testnet.snowtrace.io/address/0x3aB375D57EbB733E735a17eDFd3F973f6BC5de21)
Otoken: [0x4be9caAf7e326CE8244f82D6eC2275c4eFcA7485](https://testnet.snowtrace.io/address/0x4be9caAf7e326CE8244f82D6eC2275c4eFcA7485)
Whitelist: [0xDE24B2364eF695586cAFF591FB24d1576F69894a](https://testnet.snowtrace.io/address/0xDE24B2364eF695586cAFF591FB24d1576F69894a)
Oracle: [0x380bB2d01DC2783AB8e98f86DFaBe35DcEF0c066](https://testnet.snowtrace.io/address/0x380bB2d01DC2783AB8e98f86DFaBe35DcEF0c066)
MarginPool: [0x9EBC603bBf8309E1715a1678B5C13A4aE6c26452](https://testnet.snowtrace.io/address/0x9EBC603bBf8309E1715a1678B5C13A4aE6c26452)
MarginCalculator: [0xfCE4878C5014C438e1031876668aFA5c8cdA4c61](https://testnet.snowtrace.io/address/0xfCE4878C5014C438e1031876668aFA5c8cdA4c61)
MarginVault: [0xda4c4DD4D14472f6ca13BFeb9b90Bb84E50A7cc6](https://testnet.snowtrace.io/address/0xda4c4DD4D14472f6ca13BFeb9b90Bb84E50A7cc6)
Controller: [0x06CDdbbdC9C8032702aD9011C46eB17dc2E6b1ac](https://testnet.snowtrace.io/address/0x06CDdbbdC9C8032702aD9011C46eB17dc2E6b1ac)
OwnedUpgradeabilityProxy: [0x836E115f0580c8350228E073949bf269F7BC4B62](https://testnet.snowtrace.io/address/0x836E115f0580c8350228E073949bf269F7BC4B62)

WAVAX ChainLinkerPricer: [0x1fAEa5e3429DBabE04Bbb36D1f0A0D918640a2e9](https://testnet.snowtrace.io/address/0x1fAEa5e3429DBabE04Bbb36D1f0A0D918640a2e9)
WBTC ChainLinkerPricer: [0x0634890CF8c12F86AEfe5a3fd1F2474F12407eb5](https://testnet.snowtrace.io/address/0x0634890CF8c12F86AEfe5a3fd1F2474F12407eb5)

Owner: 0x004fcf8052d3c7ecb7558ac0068882425a055528 (ben@ribbon.finance)

**Comment by fqlx** [comment]
Please merge, I don't have write access.

**Pull request merged**
