### PR TITLE
Try to reduce controller bytecode size

### PR DESCRIPTION
**Pull request by alexisgauba**
# Task: Feature Name:

## High Level Description

Specific Changes
Function x was added ...

### Code

- [ ] Unit test 100% coverage
- [ ] Does your code follow the naming and code documentation guidelines?

### Documentation

- [ ] Is your code up to date with the spec? 
- [ ] Have you added your tests to the testing doc?

### CODE REVIEW

**Comment by antoncoding** [comment]
change optimizer run from 200 to 1 will help

**Comment by alexisgauba** [comment]
> change optimizer run from 200 to 1 will help

will increase gas tho right

**Comment by antoncoding** [comment]
yes

**Comment by alexisgauba** [comment]
> yes

ya dont think that'll work then :( lol we're so close 24.01

**Pull request closed without merging**
