### PR TITLE
[N01] Functions default to a particular case

### PR DESCRIPTION
**Pull request by haythem96**
# [N01] Functions default to a particular case

## High Level Description

This PR add the specific condition on when to:
- execute the Call action

### Code

- [x] Unit test 100% coverage
- [x] Does your code follow the naming and code documentation guidelines?

### Documentation

- [x] Is your code up to date with the spec? 
- [x] Have you added your tests to the testing doc?

### CODE REVIEW

**Comment by haythem96** [comment]
Added only a specific else statement for the ` _runActions()`.

**Review by aparnakr — COMMENTED** [review]
What about the default on month?

**Comment by haythem96** [comment]
> What about the default on month?

I don't think it is needed, also if we add an if statement for month of December, we need a condition to default for if the month is > 12. IMO better to just keep it as it is.

**Review by antoncoding — APPROVED** [review]
I don't like this PR because it will bring down our coverage ratio 😢 . But agree that having a default case is kind of dangerous

**Comment by aparnakr** [comment]
> > What about the default on month?
> 
> I don't think it is needed, also if we add an if statement for month of December, we need a condition to default for if the month is > 12. IMO better to just keep it as it is.

why don't we just require the month is 1-12? Having defaults as a code pattern seems to lead to tricky issues. 

Also are there any other places in the code that have defaults?

**Comment by haythem96** [comment]
> > > What about the default on month?
> > 
> > 
> > I don't think it is needed, also if we add an if statement for month of December, we need a condition to default for if the month is > 12. IMO better to just keep it as it is.
> 
> why don't we just require the month is 1-12? Having defaults as a code pattern seems to lead to tricky issues.
> 
> Also are there any other places in the code that have defaults?

There are no other places with default condition.
I don't think we need to restrict the month here, worst case scenario someone will send month == 13 and it will be set to December.

**Comment by aparnakr** [comment]
Eg. https://github.com/opynfinance/GammaProtocol/blob/fix/N01/contracts/libs/MarginVault.sol#L54 Do we want to be explicit here as well?

**Comment by aparnakr** [comment]
> > > > What about the default on month?
> > > 
> > > 
> > > I don't think it is needed, also if we add an if statement for month of December, we need a condition to default for if the month is > 12. IMO better to just keep it as it is.
> > 
> > 
> > why don't we just require the month is 1-12? Having defaults as a code pattern seems to lead to tricky issues.
> > Also are there any other places in the code that have defaults?
> 
> There are no other places with default condition.
> 
> I don't think we need to restrict the month here, worst case scenario someone will send month == 13 and it will be set to December.

For this example it is fine, but as a general coding pattern do we want to try to be explicit as opposed to have defaults? It seems like in other situations it could lead to more unexpected behavior if we are less explicit?

**Comment by haythem96** [comment]
> Eg. https://github.com/opynfinance/GammaProtocol/blob/fix/N01/contracts/libs/MarginVault.sol#L54 Do we want to be explicit here as well?

I updated those in Certora PR https://github.com/opynfinance/GammaProtocol/pull/271/files
We should merge it to master.

**Comment by aparnakr** [comment]
> > Eg. https://github.com/opynfinance/GammaProtocol/blob/fix/N01/contracts/libs/MarginVault.sol#L54 Do we want to be explicit here as well?
> 
> I updated those in Certora PR https://github.com/opynfinance/GammaProtocol/pull/271/files
> We should merge it to master.
 oh, can you make a PR to master from that? The certora specs branch has a lot else going on so idk if we will merge that!

**Review by aparnakr — APPROVED** [review]

**Pull request merged**
