### PR TITLE
Variable Initialization in Otoken.sol

### PR DESCRIPTION
**Pull request by AlphaSerpentis**
# Fix `uint256 trailingZeroes` Initialization in Otoken.sol

## High Level Description

- Changed `uint256 trailingZeroes = 0;` to `uint256 trailingZeroes;` for gas-saving purposes.

### Code

- [x] Unit test 100% coverage
- [x] Does your code follow the naming and code documentation guidelines?

### Documentation

- [x] Is your code up to date with the spec? 
- [x] Have you added your tests to the testing doc?

### CODE REVIEW

**Comment by haythem96** [comment]
Looks good for me! thanks for making this PR.
We will review this one and decide on which release to include it in.

**Review by haythem96 — APPROVED** [review]

**Review by aparnakr — APPROVED** [review]
Looks great! :D It will probably be included in the next audit cycle + release :)

**Comment by aparnakr** [comment]
Will confirm which release cycle this will go in + still figuring out what other changes will be batched to this file :D

**Review by antoncoding — APPROVED** [review]
LGTM

**Pull request merged**
